/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TypescriptEditorComponent {
    'baseUrl': string;
  }
}

declare global {


  interface HTMLTypescriptEditorComponentElement extends Components.TypescriptEditorComponent, HTMLStencilElement {}
  var HTMLTypescriptEditorComponentElement: {
    prototype: HTMLTypescriptEditorComponentElement;
    new (): HTMLTypescriptEditorComponentElement;
  };
  interface HTMLElementTagNameMap {
    'typescript-editor-component': HTMLTypescriptEditorComponentElement;
  }
}

declare namespace LocalJSX {
  interface TypescriptEditorComponent extends JSXBase.HTMLAttributes<HTMLTypescriptEditorComponentElement> {
    'baseUrl'?: string;
  }

  interface IntrinsicElements {
    'typescript-editor-component': TypescriptEditorComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


