/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LogComponent {
    'clear': () => Promise<void>;
    'showTimestamp': boolean;
  }
  interface TypescriptEditorComponent {
    'baseUrl': string;
    'lineCount': number;
  }
}

declare global {


  interface HTMLLogComponentElement extends Components.LogComponent, HTMLStencilElement {}
  var HTMLLogComponentElement: {
    prototype: HTMLLogComponentElement;
    new (): HTMLLogComponentElement;
  };

  interface HTMLTypescriptEditorComponentElement extends Components.TypescriptEditorComponent, HTMLStencilElement {}
  var HTMLTypescriptEditorComponentElement: {
    prototype: HTMLTypescriptEditorComponentElement;
    new (): HTMLTypescriptEditorComponentElement;
  };
  interface HTMLElementTagNameMap {
    'log-component': HTMLLogComponentElement;
    'typescript-editor-component': HTMLTypescriptEditorComponentElement;
  }
}

declare namespace LocalJSX {
  interface LogComponent extends JSXBase.HTMLAttributes<HTMLLogComponentElement> {
    'showTimestamp'?: boolean;
  }
  interface TypescriptEditorComponent extends JSXBase.HTMLAttributes<HTMLTypescriptEditorComponentElement> {
    'baseUrl'?: string;
    'lineCount'?: number;
  }

  interface IntrinsicElements {
    'log-component': LogComponent;
    'typescript-editor-component': TypescriptEditorComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


